apiVersion: v1 
kind: Service 
metadata:  
  labels:  
    app: kafkaApp 
  name: kafka
spec:  
  ports:  
    -  
     name: test1
     port: 9092 
     targetPort: 9092
     protocol: TCP
    -  
     name: test2
     port: 2181 
     targetPort: 2181 
  selector:  
    app: kafkaApp 
  type: LoadBalancer
